### ISSUE TITLE
Create Gantt Chart

### ISSUE THREAD

**Issue by harriswe** [xStaticVoid/Farkle#23]
We need to create a Gantt chart for the tasks etc that we did.

**Comment by xStaticVoid** [comment]
Done and done.  All in a fancy-shmancy spreadsheet found here: https://docs.google.com/a/mail.gvsu.edu/spreadsheets/d/1TYdr_CpB-FWWk-AgHcxM180AIU_HTP28J5MbKM251FE/edit?usp=sharing
