### ISSUE TITLE
Clean up code according to checkstyle guidelines. 

### ISSUE THREAD

**Issue by harriswe** [xStaticVoid/Farkle#39]
**Instructions for using Custom Checkstyle configuration settings in IntelliJ IDEA:**

- Download Check Style-IDEA plugin for IntelliJ here: https://plugins.jetbrains.com/plugin/1065-checkstyle-idea
- Navigate to Settings -> Editor -> Code Style -> Make sure Scheme is Default.
- At the very bottom of settings, Checkstyle -> Checkstyle version: 8.0 -> Scan Scope: Only Java sources.
- Click the green + on the right to add a configuration file. Use the file located in Farkle -> CheckStyle folder.

VIOLA custom checkstyle configuration in IntelliJ

**Comment by harriswe** [comment]
So this might  mean adding "CHECKSTYLE\:OFF" or "CHECKSTYLE\:ON" in a comment to turn it on or off. You can also turn real time scanning in intelliJ on or off.

**Comment by huttonb** [comment]
After you download checkstyle you should just have to pull the checkstyle header and it will have the configuration in your settings.

**Comment by harriswe** [comment]
Done.
